### ISSUE TITLE
Single archive download containing binaries for multiple OS

### ISSUE THREAD

**Issue by Hiradur** [MegaGlest/megaglest-source#140]
[OpenArena](http://openarena.ws/download.php) and [Xonotic](http://xonotic.org/) provide a single download for Windows, macOS and Linux. A single archive contains both i386 and amd64 binaries for these operating systems. This makes it very easy to share the game and ensure everybody is using the same version, e.g. at LAN parties.

It would be nice if MegaGlest would also provide a single archive for download with binaries for multiple operating systems.

**Comment by titiger** [comment]
How does something like this help? We have binary packages, data package and installers. Is this not enough?

**Comment by Hiradur** [comment]
> How does something like this help?

The use case would be to make it easier to share the game with people using different operating systems. Take OpenArena for example. With one archive Windows, macOS and Linux 32/64 Bit are covered. It's also free and legal to share it due to the GPL. This makes it a good game to share with people. It doesn't matter which operating system they use and they also don't need to set it up beforehand. They can just copy the archive and play. I think this is beneficial to expanding the community of a game and it's probably also a unique property of FOSS games, demonstrating the advantages of free software as a whole.

**Comment by tomreyn** [comment]
My opinion is not authoritative, but I'll add it to the discussion...
At this time, we provide, for Linux, Windows and OS X, two installation methods:

- two archive files (keeping these separate makes sense for testing so we do not always need to build / package both at the same time) which, unpacked and combined, provide a working game, targeting technically advanced users who prefer to not run additional software just to make a software usable
- an "installer" type installation, targeting less technically adept users who prefer an 'installation routine'

With this, we already maintain several formats, which no better alternative seems to exist for. Adding another format would increase the packaging (disk I/O, CPU time, storage space) overhead, to create a package format which is pretty similar to the first one discussed above. I am not currently convinced that the benefit this would bring is actually worth it. 

I am also not strictly against it since the additional overhead is probably rather small. However, someone would need to set it up in Jenkins / with additional packaging scripts initially (and currently I do not see any volunteers for this job).

**Comment by titiger** [comment]
I suggest we close this as noone in the team sees a big need for this and is willing to work on it at the moment
