### ISSUE TITLE
upgrade states not saved if upgrade is in progress

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#155]
I noticed this while playing the Amazones scenario on git.

To reproduce:

1. From the blacksmith, when sharpen points is at 2% (or 5 or 10, etc), save the game.
2. now exit
3. Load the saved game. You'll see the upgrade went back to 0%.

**Comment by andy5995** [comment]
Te test this further, I started the scenario Egypt Mayhem.

I started the uprades: research scarab, increase priest production, and sharpen edges.

I saved the game while all 3 were in progress. When I re-loaded, all 3 upgrades had reset to 0%

**Comment by Rampoina** [comment]
Ok first of all it's not only upgrades, it's the progress for any unit (including buildings):
The progress for a unit being built doesn't get saved  either for example.

The issue is that when loading the game the `setCurrSkill` [function](https://github.com/MegaGlest/megaglest-source/blob/develop/source/glest_game/type_instances/unit.cpp#L5345) overrides the previously restored `progress2` variable.
This happens [here](https://github.com/MegaGlest/megaglest-source/blob/develop/source/glest_game/type_instances/unit.cpp#L1340)
I've worked around it in #244 but I'm not sure why that line is there in the first place (why is it set to 0).
