### ISSUE TITLE
workers don't respond to harvest commands if main building is gone

### ISSUE THREAD

**Issue by andy5995** [MegaGlest/megaglest-source#159]
The following situation may appear at first as a bug to some users:

They have a blacksmith, but can not harvest wood because their first castle was destroyed, but a new one is being built.

In fact, clicking workers and telling them to harvest wood or gold does nothing. They just stand there.

My proposal is a message in the lower left corner that displays if a user tries to mine when they are waiting for a new main building to complete construction:  "No storage unit currently available."

Edit/ Update: The following paragraph was more like a feature request so I've deleted it  and will post it in the forum.

**Comment by titiger** [comment]
This is not 100 % correct. They start mining and so on if they are not fully loaded! But if they are loaded they cannot carry more. But then they cannot bring their loaded resources to a storage building.
So printing "No storage unit currently available." on click is maybe a bit hard to do. What happens is : they get the command and abort it, because no storage is there. But this is decided for every unit on its own. So if we print this to console every time a units needs to abort his mining command we will see many many lines in the console.

**Comment by andy5995** [comment]
@titiger and I discussed this a little more and he suggested it to be a feature request more than a bug I'll make a note of it on the forum. It's a very low priority feature request and definitely doesn't need to be looked at before the Steam release.
