### ISSUE TITLE
Editor fails to launch on Steam (Ubuntu 16.04.2 x86_64)

### ISSUE THREAD

**Issue by tomreyn** [MegaGlest/megaglest-source#166]
On the Steam dev channel we currently have the default 3.12.0 release build. When I double-click MegaGlest on Steam it presents a popup allowing me to either start the game or the (map) editor. When I choose to start the (map) editor, the prompt closes and nothing else happens.

If I log the output of what happens there to a file, I get to see this:
```
ERROR: ld.so: object '/home/tomreyn/.steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
15:26:16: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
Segmentation fault
```

My understanding is that the first line is unrelated, caused by Steam' LDD preload voodoo. However, the follow up lines may hint at what is going wrong. Since this is a SegFault, I guess I could try and spawn the editor through gdb instead, prodocing a core file, then analysing that. Let me know if I should give this a try.

**Comment by filux** [comment]
Steam does not contain own version of wxwidgets. Those in the MG's 'bin' directory are taken into account on the very end of searching process (if nothing was found before).
... so editor should start if:
- there isn't a native version of wx installed from the distro (then wx version from 'bin' is used),
- when wx are installed but in "old" compatible (to gcc used by MG) version,
- ... when you use our start script :D, which is not tolerated by steam ... just a plain racism :D.

... so summing up in this situation with steam on my eye editor should start for everyone who don't have own wxwidgets installed ...and for all others there is a chance like 30% to start editor and this chance decreases in time because more and more linux releases with incompatible wx.

**Comment by titiger** [comment]
SO is it maybe better to use a 2.8wxwidget for steam editor ?
Newer linuxes don't have the 2.8 and by this our lib in "bin" would be used.
For older linuxes 2.8 works too because their 2.8 is compatible with ours.

**Comment by tomreyn** [comment]
Softcoder reworked static builds on Linux, just for the editor and viewer for now. Running `mk/linux/build_mg.sh  -s` will (assuming wx-dev is available) create static builds for them. If produced on Ubuntu 14.04 x86_64, they seem to work fine for both Ubuntu 14.04 and 16.04, which should be good enough for these two tools on Steam on Linux.
