### ISSUE TITLE
3.13.0, Fedora 36, Crash on start

### ISSUE THREAD

**Issue by balintbarna** [MegaGlest/megaglest-source#262]
I'm running an up to date Fedora 36 Workstation edition on my desktop PC.
I tried 2 approaches to install megaglest. First I tried through the graphical software manager, searched for megaglest and clicked install. 
This should automatically install the RPM package. Seemingly the install succeeds, but there are no shortcuts created and the "Open" button is unavailable on the graphical interface.

After uninstalling it from the graphical interface, I tried through the terminal with `sudo dnf install megaglest`. This succeeds seemingly and the launcher icons are generated, however after clicking the icon to start the game I get the following error message:

```
Error msg = [Unknown error
Stack Trace:
megaglest:Glest::Game::ExceptionHandler::handleRuntimeError(char const*, bool)address [0x5578a2549d74] line: 0
megaglest:()address [0x5578a22bc4c0] line: 0
megaglest:Glest::Game::glestMainSEHWrapper(int, char**)address [0x5578a2584b06] line: 0
/lib64/libc.so.6:()address [0x7f84cae29510] line: 0
/lib64/libc.so.6:__libc_start_main()address [0x7f84cae295c9] line: 0
megaglest:_start()address [0x5578a23b6af5] line: 0
]

Please report this bug to  http://bugs.megaglest.org
```

versions:

```
Installed:
  megaglest-3.13.0-12.fc36.x86_64      megaglest-data-3.13.0-8.fc36.noarch
```

**Comment by Jammyjamjamman** [comment]
Apologies for the very late reply. Unfortunately, the fedora release is not maintained by us.

If you want to try running the game, I'd recommend one of the following options:
* Try the linux installer from the website: https://megaglest.org/download
* Compile yourself (the "quick setup" entry here provides an easy set of commands to copy-paste, in order to build the game): https://docs.megaglest.org/index.php?title=MG/Linux_Compiling
* Try the AppImage snapshot: https://github.com/MegaGlest/megaglest-source/releases/tag/snapshot

Note the last 2 options are development builds, so they will be incompatible with the latest release.
