### ISSUE TITLE
megaglest 3.11.1-1 still dependant on VLC

### ISSUE THREAD

**Issue by wrapperband** [MegaGlest/megaglest-source#69]
Had to try removing VLC and Megaglest and megaglest-data was dependant, version 3.11 from getdeb, on Kubuntu 15.04

ie re: 3.11.1-1-getdeb2-vivid

```
From: Markus Koschany <apo@gam[REDACTED].de>
To: 723790-close@bugs.deb[REDACTED].org
Subject: Bug#723790: fixed in megaglest 3.9.1-1
Date: Fri, 03 Oct 2014 21:22:45 +0000

Source: megaglest
Source-Version: 3.9.1-1

We believe that the bug you reported is fixed in the latest version of
megaglest, which is due to be installed in the Debian FTP archive.
```

**Comment by tomreyn** [comment]
If you would like to suggest changes to how GetDeb packages are packaged, please contact GetDeb (the same goes for Debian), since we do not manage these packages. Thank you.

http://www.getdeb.net/contact/

(I also took the liberty of redacting the e-mail addresses you had posted here to prevent harvesting / spam.)
